name: Checkov Security Tests

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - published

jobs:
  security-tests:
    name: security-tests
    runs-on: comcast-ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkov tests
        uses: bridgecrewio/checkov-action@v12
        with:
          framework: terraform
