name: Terratests

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - published

env:
  AWS_REGION: us-east-1

jobs:
  terratests:
    name: terratests
    strategy:
      fail-fast: false
      matrix:
        binary: ["tofu", "terraform"]
        version: ["1.6", "1.7"]
        experimental: [false]
        include:
          - version: "1.8"
            engine: "terraform"
            experimental: false
          - version: "1.9"
            binary: "terraform"
            experimental: false

    runs-on: comcast-ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      ## Uncomment to use AWS. Make sure to add AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to your repository secrets
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-region: ${{ env.AWS_REGION }}
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        if: ${{ matrix.binary == 'terraform' }}
        with:
          terraform_version: ${{ matrix.version }}

      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        if: ${{ matrix.binary == 'tofu' }}
        with:
          tofu_version: ${{ matrix.version }}
          tofu_wrapper: false

        # If the Terraform binary is not present but OpenTofu is, terratest defaults to using tofu.
      - name: Uninstall Terraform
        if: ${{ matrix.binary == 'tofu' }}
        run: sudo rm -rf $(which terraform)

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.21.0"

      - name: Go Init Modules
        working-directory: terratest
        run: go mod init github.com/comcast-github-actions-community/gha-terraform-example/tests

      - name: Go Tidy Packages
        working-directory: terratest
        run: go mod tidy

      - name: Run Tests
        run: make terratest TF_BINARY=${{ matrix.binary }}
